# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OC-LongImage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OC-LongImage
  pod 'SDWebImage', '5.19.4'
  pod 'FLAnimatedImage', '1.0.17'

end
